spring.application.name=notification-service
server.port=8083
spring.datasource.url=jdbc:h2:mem:notificationdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.h2.console.enabled=true
notification.worker.pool-size=4
notification.worker.idle-delay-ms=150
notification.worker.processing-delay-ms=80
notification.integration.events.exchange=trip.events
notification.integration.events.queue=notification.trip-status.queue
notification.integration.events.routing-key=trip.status.changed
