services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  user-service:
    build:
      context: .
      dockerfile: user-service/Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8081:8081"
    depends_on:
      - redis

  notification-service:
    build:
      context: .
      dockerfile: notification-service/Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_RABBITMQ_HOST: rabbitmq
    ports:
      - "8083:8083"
    depends_on:
      - redis
      - rabbitmq

  trip-service:
    build:
      context: .
      dockerfile: trip-service/Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_CACHE_TYPE: redis
      SPRING_DATA_REDIS_HOST: redis
      SPRING_RABBITMQ_HOST: rabbitmq
      TRIP_INTEGRATION_USER_BASE_URL: http://user-service:8081
      TRIP_INTEGRATION_USER_SYNC_ENABLED: "true"
      SECURITY_JWT_SECRET: ChangeThisSecretKeyToAtLeast32BytesForHS256
      SECURITY_JWT_EXPIRATION_SECONDS: 3600
    ports:
      - "8082:8082"
    depends_on:
      - redis
      - rabbitmq
      - notification-service
